/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mongo.gltf --transform
Author: Amiel Goco (https://sketchfab.com/pamikoe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-filing-cabinet-619484b78fbe449ea5c0cdb68e8f2bd6
Title: Rusty Filing Cabinet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mongo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.62}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.drawer_04_low_mat_drawers_0.geometry} material={materials.mat_drawers} position={[0, 0, 15]} />
          <mesh geometry={nodes.drawer_03_low_mat_drawers_0.geometry} material={materials.mat_drawers} position={[0, 0, 4]} />
          <mesh geometry={nodes.drawer_02_low_mat_drawers_0.geometry} material={materials.mat_drawers} position={[0, 0, 11]} />
          <mesh geometry={nodes.cabinet_low_mat_cabinet_0.geometry} material={materials.mat_cabinet} />
          <mesh geometry={nodes.drawer_01_low_mat_drawers_0.geometry} material={materials.mat_drawers} position={[0, 0, 5]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mongo-transformed.glb')
