/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 node.gltf --transform
Author: sanyaork (https://sketchfab.com/sanyaork)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/server-box-8b1ddae9098a4c89815f9751342237bf
Title: Server box
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/node.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['��������_������������������_������������_0'].geometry} material={materials.material_1} />
        <mesh geometry={nodes['��������_glass_0'].geometry} material={materials.glass} />
      </group>
      <group position={[40.22, 127.57, 34.54]} rotation={[-Math.PI / 2, 0, 0.43]} scale={100}>
        <mesh geometry={nodes['����������_3_������������������_������������_0'].geometry} material={materials.material_1} />
        <mesh geometry={nodes['����������_3_glass_0'].geometry} material={materials.glass} />
      </group>
      <mesh geometry={nodes['������������_������������_0'].geometry} material={materials.material} position={[0, 23.58, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['����������1_������������������_������������_0'].geometry} material={materials.material_1} position={[-42.5, 73.54, -31.78]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['����������2_������������������_������������_0'].geometry} material={materials.material_1} position={[-42.5, 162.11, -31.71]} rotation={[-Math.PI / 2, 0, -0.53]} scale={100} />
      <mesh geometry={nodes['������������001_������������_0'].geometry} material={materials.material} position={[0, 40.74, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
      <mesh geometry={nodes['������������003_������������_0'].geometry} material={materials.material} position={[0, 172.43, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['������������004_������������_0'].geometry} material={materials.material} position={[0, 189.72, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
      <mesh geometry={nodes['������������005_������������_0'].geometry} material={materials.material} position={[0, 206.85, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['��������������_��������������__0'].geometry} material={materials.material_3} position={[8.49, 104.73, -0.09]} rotation={[-Math.PI / 2, 0, -0.32]} scale={84.18} />
      <mesh geometry={nodes['��������������������_��������������������_0'].geometry} material={materials.material_4} position={[-12.95, 104.54, 16.09]} rotation={[-Math.PI / 2, 0, -0.13]} scale={56.5} />
    </group>
  )
}

useGLTF.preload('/node-transformed.glb')
